# Generated by Django 3.2.6 on 2021-11-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request_url', models.CharField(max_length=200)),
                ('request_body', models.CharField(max_length=500)),
                ('response_code', models.PositiveSmallIntegerField()),
                ('error_detail', models.CharField(max_length=500)),
            ],
        ),
    ]
