# Generated by Django 3.2.6 on 2021-09-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0005_auto_20210925_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='participant_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
