# Generated by Django 3.2.6 on 2021-09-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0006_seminar_participant_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='participant_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
