# Generated by Django 3.2.6 on 2021-09-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0007_auto_20210927_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='online',
            field=models.BooleanField(null=True),
        ),
    ]
