# Generated by Django 3.2.6 on 2021-09-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='participant', max_length=30),
            preserve_default=False,
        ),
    ]
