# Generated by Django 3.2.6 on 2021-09-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210925_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
