# Generated by Django 3.2.6 on 2021-09-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_instructorprofile_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantprofile',
            name='accepted',
            field=models.BooleanField(null=True),
        ),
    ]
