# Generated by Django 3.2.6 on 2021-09-25 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_participantprofile_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
