# Generated by Django 3.2.6 on 2021-09-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantprofile',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
    ]
