# Generated by Django 3.2.6 on 2021-11-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_surveyresult_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatingsystem',
            name='foobar',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
