name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-host:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
            MYSQL_DATABASE: 'waffle_backend_2'
            MYSQL_USER: 'waffle-backend'
            MYSQL_PASSWORD: 'seminar'
            MYSQL_ROOT_PASSWORD: password
        ports:
            - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - name: Verify MySQL connection
      run: |
        mysql --version
        sudo apt-get install -y mysql-client

    - name: MySQL Grant
      run: | 
        sudo mysql -h 127.0.0.1 --port 3306 -u root -ppassword -e """GRANT ALL PRIVILEGES ON *.* TO 'waffle-backend'@'%' WITH GRANT OPTION;"""
                
    - name: Set up Python 3.8.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.10

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Tests
      run: |
        coverage run manage.py test
        coverage report
      env:
        SYSTEM_ENV: GITHUB_WORKFLOW
